vim.opt.relativenumber=true
vim.opt.smartindent=true
vim.opt.incsearch=true
vim.opt.tabstop=4
vim.opt.softtabstop=4
vim.opt.shiftwidth=4
vim.opt.expandtab=true
vim.opt.listchars.eol="↴"
vim.opt.listchars.tab="➔ "
vim.opt.listchars.trail="~"
vim.opt.listchars.extends="»"
vim.opt.listchars.precedes="«"
vim.opt.listchars.space="·"
vim.opt.clipboard={unnamed,unnamedplus}
vim.opt.spelllang="en_gb"
vim.opt.showmode=true               
vim.opt.autochdir=true
vim.opt.hidden=true
vim.opt.wrap=true
vim.opt.list=true      

