# -*- mode: shell-script; -*-

# Source .bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc

# Set environment variables
wofiscripts="${HOME}/.config/wofi/scripts"
scripts="${HOME}/repositories/scripts:${wofiscripts}"
export PATH="${scripts}:${PATH}"
export EDITOR=nano
export VISUAL=nano

# Run window manager
if [ "$(tty)" = "/dev/tty1" ]; then
		dbus-run-session sway
fi
