# -*- mode: shell-script; -*-

# Source .bashrc
[[ -f ~/.bashrc ]] && source ~/.bashrc

# Set environment variables
SCRIPTS="${HOME}/repositories/scripts"
export PATH="${SCRIPTS}:${PATH}"
export EDITOR=emacs
export VISUAL=emacs
